// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oFUojo7aVsD6ehtiM6NzP7
// Component: H_wdk83Ky7Hk
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: oFUojo7aVsD6ehtiM6NzP7/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: H_wdk83Ky7Hk/css

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

export const defaultHomepage__Args = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultHomepage__Args, props.args);
  const $props = args;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"frame"}
            data-plasmic-override={overrides.frame}
            className={classNames(projectcss.all, sty.frame)}
          >
            <div
              data-plasmic-name={"rectangle"}
              data-plasmic-override={overrides.rectangle}
              className={classNames(projectcss.all, sty.rectangle)}
            />

            <div
              data-plasmic-name={"rectangle2"}
              data-plasmic-override={overrides.rectangle2}
              className={classNames(projectcss.all, sty.rectangle2)}
            />

            <div
              data-plasmic-name={"image"}
              data-plasmic-override={overrides.image}
              className={classNames(projectcss.all, sty.image)}
            />

            <div
              data-plasmic-name={"rectangle3"}
              data-plasmic-override={overrides.rectangle3}
              className={classNames(projectcss.all, sty.rectangle3)}
            />

            <div
              data-plasmic-name={"image2"}
              data-plasmic-override={overrides.image2}
              className={classNames(projectcss.all, sty.image2)}
            />

            <div
              data-plasmic-name={"rectangle4"}
              data-plasmic-override={overrides.rectangle4}
              className={classNames(projectcss.all, sty.rectangle4)}
            />

            <div
              data-plasmic-name={"rectangle5"}
              data-plasmic-override={overrides.rectangle5}
              className={classNames(projectcss.all, sty.rectangle5)}
            />

            <div
              data-plasmic-name={"rectangle6"}
              data-plasmic-override={overrides.rectangle6}
              className={classNames(projectcss.all, sty.rectangle6)}
            />

            <div
              data-plasmic-name={"rectangle7"}
              data-plasmic-override={overrides.rectangle7}
              className={classNames(projectcss.all, sty.rectangle7)}
            />

            <div
              data-plasmic-name={"rectangle8"}
              data-plasmic-override={overrides.rectangle8}
              className={classNames(projectcss.all, sty.rectangle8)}
            />

            <div
              data-plasmic-name={"rectangle9"}
              data-plasmic-override={overrides.rectangle9}
              className={classNames(projectcss.all, sty.rectangle9)}
            />

            <div
              data-plasmic-name={"rectangle10"}
              data-plasmic-override={overrides.rectangle10}
              className={classNames(projectcss.all, sty.rectangle10)}
            />

            <div
              data-plasmic-name={"image3"}
              data-plasmic-override={overrides.image3}
              className={classNames(projectcss.all, sty.image3)}
            />

            <div
              data-plasmic-name={"rectangle11"}
              data-plasmic-override={overrides.rectangle11}
              className={classNames(projectcss.all, sty.rectangle11)}
            />

            <div
              data-plasmic-name={"image4"}
              data-plasmic-override={overrides.image4}
              className={classNames(projectcss.all, sty.image4)}
            />

            <div
              data-plasmic-name={"rectangle12"}
              data-plasmic-override={overrides.rectangle12}
              className={classNames(projectcss.all, sty.rectangle12)}
            />

            <div
              data-plasmic-name={"image5"}
              data-plasmic-override={overrides.image5}
              className={classNames(projectcss.all, sty.image5)}
            />

            <div
              data-plasmic-name={"rectangle13"}
              data-plasmic-override={overrides.rectangle13}
              className={classNames(projectcss.all, sty.rectangle13)}
            />

            <div
              data-plasmic-name={"image6"}
              data-plasmic-override={overrides.image6}
              className={classNames(projectcss.all, sty.image6)}
            />

            <div
              data-plasmic-name={"rectangle14"}
              data-plasmic-override={overrides.rectangle14}
              className={classNames(projectcss.all, sty.rectangle14)}
            />

            <div
              data-plasmic-name={"image7"}
              data-plasmic-override={overrides.image7}
              className={classNames(projectcss.all, sty.image7)}
            />

            <div
              data-plasmic-name={"rectangle15"}
              data-plasmic-override={overrides.rectangle15}
              className={classNames(projectcss.all, sty.rectangle15)}
            />

            <div
              data-plasmic-name={"image8"}
              data-plasmic-override={overrides.image8}
              className={classNames(projectcss.all, sty.image8)}
            />

            <div
              data-plasmic-name={"rectangle16"}
              data-plasmic-override={overrides.rectangle16}
              className={classNames(projectcss.all, sty.rectangle16)}
            />

            <div
              data-plasmic-name={"image9"}
              data-plasmic-override={overrides.image9}
              className={classNames(projectcss.all, sty.image9)}
            />

            <div
              data-plasmic-name={"rectangle17"}
              data-plasmic-override={overrides.rectangle17}
              className={classNames(projectcss.all, sty.rectangle17)}
            />

            <div
              data-plasmic-name={"rectangle18"}
              data-plasmic-override={overrides.rectangle18}
              className={classNames(projectcss.all, sty.rectangle18)}
            />

            <div
              data-plasmic-name={"rectangle19"}
              data-plasmic-override={overrides.rectangle19}
              className={classNames(projectcss.all, sty.rectangle19)}
            />

            <div
              data-plasmic-name={"rectangle20"}
              data-plasmic-override={overrides.rectangle20}
              className={classNames(projectcss.all, sty.rectangle20)}
            />

            <div
              data-plasmic-name={"rectangle21"}
              data-plasmic-override={overrides.rectangle21}
              className={classNames(projectcss.all, sty.rectangle21)}
            />

            <div
              data-plasmic-name={"rectangle22"}
              data-plasmic-override={overrides.rectangle22}
              className={classNames(projectcss.all, sty.rectangle22)}
            />

            <div
              data-plasmic-name={"rectangle23"}
              data-plasmic-override={overrides.rectangle23}
              className={classNames(projectcss.all, sty.rectangle23)}
            />

            <div
              data-plasmic-name={"rectangle24"}
              data-plasmic-override={overrides.rectangle24}
              className={classNames(projectcss.all, sty.rectangle24)}
            />

            <div
              data-plasmic-name={"rectangle25"}
              data-plasmic-override={overrides.rectangle25}
              className={classNames(projectcss.all, sty.rectangle25)}
            />

            <div
              data-plasmic-name={"rectangle26"}
              data-plasmic-override={overrides.rectangle26}
              className={classNames(projectcss.all, sty.rectangle26)}
            />

            <div
              data-plasmic-name={"rectangle27"}
              data-plasmic-override={overrides.rectangle27}
              className={classNames(projectcss.all, sty.rectangle27)}
            />

            <div
              data-plasmic-name={"rectangle28"}
              data-plasmic-override={overrides.rectangle28}
              className={classNames(projectcss.all, sty.rectangle28)}
            />

            <div
              data-plasmic-name={"rectangle29"}
              data-plasmic-override={overrides.rectangle29}
              className={classNames(projectcss.all, sty.rectangle29)}
            />

            <div
              data-plasmic-name={"image10"}
              data-plasmic-override={overrides.image10}
              className={classNames(projectcss.all, sty.image10)}
            />

            <div
              data-plasmic-name={"image11"}
              data-plasmic-override={overrides.image11}
              className={classNames(projectcss.all, sty.image11)}
            />

            <div
              data-plasmic-name={"rectangle30"}
              data-plasmic-override={overrides.rectangle30}
              className={classNames(projectcss.all, sty.rectangle30)}
            />

            <div
              data-plasmic-name={"image12"}
              data-plasmic-override={overrides.image12}
              className={classNames(projectcss.all, sty.image12)}
            />

            <div
              data-plasmic-name={"image13"}
              data-plasmic-override={overrides.image13}
              className={classNames(projectcss.all, sty.image13)}
            />

            <div
              data-plasmic-name={"rectangle31"}
              data-plasmic-override={overrides.rectangle31}
              className={classNames(projectcss.all, sty.rectangle31)}
            />

            <div
              data-plasmic-name={"image14"}
              data-plasmic-override={overrides.image14}
              className={classNames(projectcss.all, sty.image14)}
            />

            <div
              data-plasmic-name={"image15"}
              data-plasmic-override={overrides.image15}
              className={classNames(projectcss.all, sty.image15)}
            />

            <div
              data-plasmic-name={"rectangle32"}
              data-plasmic-override={overrides.rectangle32}
              className={classNames(projectcss.all, sty.rectangle32)}
            />

            <div
              data-plasmic-name={"image16"}
              data-plasmic-override={overrides.image16}
              className={classNames(projectcss.all, sty.image16)}
            />

            <div
              data-plasmic-name={"image17"}
              data-plasmic-override={overrides.image17}
              className={classNames(projectcss.all, sty.image17)}
            />

            <div
              data-plasmic-name={"rectangle33"}
              data-plasmic-override={overrides.rectangle33}
              className={classNames(projectcss.all, sty.rectangle33)}
            />

            <div
              data-plasmic-name={"image18"}
              data-plasmic-override={overrides.image18}
              className={classNames(projectcss.all, sty.image18)}
            />

            <div
              data-plasmic-name={"image19"}
              data-plasmic-override={overrides.image19}
              className={classNames(projectcss.all, sty.image19)}
            />

            <div
              data-plasmic-name={"rectangle34"}
              data-plasmic-override={overrides.rectangle34}
              className={classNames(projectcss.all, sty.rectangle34)}
            />

            <div
              data-plasmic-name={"image20"}
              data-plasmic-override={overrides.image20}
              className={classNames(projectcss.all, sty.image20)}
            />

            <div
              data-plasmic-name={"image21"}
              data-plasmic-override={overrides.image21}
              className={classNames(projectcss.all, sty.image21)}
            />

            <div
              data-plasmic-name={"rectangle35"}
              data-plasmic-override={overrides.rectangle35}
              className={classNames(projectcss.all, sty.rectangle35)}
            />

            <div
              data-plasmic-name={"image22"}
              data-plasmic-override={overrides.image22}
              className={classNames(projectcss.all, sty.image22)}
            />

            <div
              data-plasmic-name={"image23"}
              data-plasmic-override={overrides.image23}
              className={classNames(projectcss.all, sty.image23)}
            />

            <div
              data-plasmic-name={"rectangle36"}
              data-plasmic-override={overrides.rectangle36}
              className={classNames(projectcss.all, sty.rectangle36)}
            />

            <div
              data-plasmic-name={"image24"}
              data-plasmic-override={overrides.image24}
              className={classNames(projectcss.all, sty.image24)}
            />

            <div
              data-plasmic-name={"image25"}
              data-plasmic-override={overrides.image25}
              className={classNames(projectcss.all, sty.image25)}
            />

            <div
              data-plasmic-name={"image26"}
              data-plasmic-override={overrides.image26}
              className={classNames(projectcss.all, sty.image26)}
            />

            <div
              data-plasmic-name={"rectangle37"}
              data-plasmic-override={overrides.rectangle37}
              className={classNames(projectcss.all, sty.rectangle37)}
            />

            <div
              data-plasmic-name={"rectangle38"}
              data-plasmic-override={overrides.rectangle38}
              className={classNames(projectcss.all, sty.rectangle38)}
            />

            <div
              data-plasmic-name={"rectangle39"}
              data-plasmic-override={overrides.rectangle39}
              className={classNames(projectcss.all, sty.rectangle39)}
            />

            <div
              data-plasmic-name={"rectangle40"}
              data-plasmic-override={overrides.rectangle40}
              className={classNames(projectcss.all, sty.rectangle40)}
            />

            <div
              data-plasmic-name={"rectangle41"}
              data-plasmic-override={overrides.rectangle41}
              className={classNames(projectcss.all, sty.rectangle41)}
            />

            <div
              data-plasmic-name={"rectangle42"}
              data-plasmic-override={overrides.rectangle42}
              className={classNames(projectcss.all, sty.rectangle42)}
            />

            <div
              data-plasmic-name={"rectangle43"}
              data-plasmic-override={overrides.rectangle43}
              className={classNames(projectcss.all, sty.rectangle43)}
            />

            <div
              data-plasmic-name={"rectangle44"}
              data-plasmic-override={overrides.rectangle44}
              className={classNames(projectcss.all, sty.rectangle44)}
            />

            <div
              data-plasmic-name={"image27"}
              data-plasmic-override={overrides.image27}
              className={classNames(projectcss.all, sty.image27)}
            />

            <div
              data-plasmic-name={"rectangle45"}
              data-plasmic-override={overrides.rectangle45}
              className={classNames(projectcss.all, sty.rectangle45)}
            />

            <div
              data-plasmic-name={"image28"}
              data-plasmic-override={overrides.image28}
              className={classNames(projectcss.all, sty.image28)}
            />

            <div
              data-plasmic-name={"rectangle46"}
              data-plasmic-override={overrides.rectangle46}
              className={classNames(projectcss.all, sty.rectangle46)}
            />

            <div
              data-plasmic-name={"image29"}
              data-plasmic-override={overrides.image29}
              className={classNames(projectcss.all, sty.image29)}
            />

            <div
              data-plasmic-name={"rectangle47"}
              data-plasmic-override={overrides.rectangle47}
              className={classNames(projectcss.all, sty.rectangle47)}
            />

            <div
              data-plasmic-name={"image30"}
              data-plasmic-override={overrides.image30}
              className={classNames(projectcss.all, sty.image30)}
            />

            <div
              data-plasmic-name={"rectangle48"}
              data-plasmic-override={overrides.rectangle48}
              className={classNames(projectcss.all, sty.rectangle48)}
            />

            <div
              data-plasmic-name={"rectangle49"}
              data-plasmic-override={overrides.rectangle49}
              className={classNames(projectcss.all, sty.rectangle49)}
            />

            <div
              data-plasmic-name={"rectangle50"}
              data-plasmic-override={overrides.rectangle50}
              className={classNames(projectcss.all, sty.rectangle50)}
            />

            <div
              data-plasmic-name={"rectangle51"}
              data-plasmic-override={overrides.rectangle51}
              className={classNames(projectcss.all, sty.rectangle51)}
            />

            <div
              data-plasmic-name={"rectangle52"}
              data-plasmic-override={overrides.rectangle52}
              className={classNames(projectcss.all, sty.rectangle52)}
            />

            <div
              data-plasmic-name={"rectangle53"}
              data-plasmic-override={overrides.rectangle53}
              className={classNames(projectcss.all, sty.rectangle53)}
            />

            <div
              data-plasmic-name={"rectangle54"}
              data-plasmic-override={overrides.rectangle54}
              className={classNames(projectcss.all, sty.rectangle54)}
            />

            <div
              data-plasmic-name={"rectangle55"}
              data-plasmic-override={overrides.rectangle55}
              className={classNames(projectcss.all, sty.rectangle55)}
            />

            <div
              data-plasmic-name={"image31"}
              data-plasmic-override={overrides.image31}
              className={classNames(projectcss.all, sty.image31)}
            />

            <div
              data-plasmic-name={"image32"}
              data-plasmic-override={overrides.image32}
              className={classNames(projectcss.all, sty.image32)}
            />

            <div
              data-plasmic-name={"rectangle56"}
              data-plasmic-override={overrides.rectangle56}
              className={classNames(projectcss.all, sty.rectangle56)}
            />

            <div
              data-plasmic-name={"image33"}
              data-plasmic-override={overrides.image33}
              className={classNames(projectcss.all, sty.image33)}
            />

            <div
              data-plasmic-name={"image34"}
              data-plasmic-override={overrides.image34}
              className={classNames(projectcss.all, sty.image34)}
            />

            <div
              data-plasmic-name={"rectangle57"}
              data-plasmic-override={overrides.rectangle57}
              className={classNames(projectcss.all, sty.rectangle57)}
            />

            <div
              data-plasmic-name={"image35"}
              data-plasmic-override={overrides.image35}
              className={classNames(projectcss.all, sty.image35)}
            />

            <div
              data-plasmic-name={"image36"}
              data-plasmic-override={overrides.image36}
              className={classNames(projectcss.all, sty.image36)}
            />

            <div
              data-plasmic-name={"rectangle58"}
              data-plasmic-override={overrides.rectangle58}
              className={classNames(projectcss.all, sty.rectangle58)}
            />

            <div
              data-plasmic-name={"image37"}
              data-plasmic-override={overrides.image37}
              className={classNames(projectcss.all, sty.image37)}
            />

            <div
              data-plasmic-name={"image38"}
              data-plasmic-override={overrides.image38}
              className={classNames(projectcss.all, sty.image38)}
            />

            <div
              data-plasmic-name={"image39"}
              data-plasmic-override={overrides.image39}
              className={classNames(projectcss.all, sty.image39)}
            />

            <div
              data-plasmic-name={"image40"}
              data-plasmic-override={overrides.image40}
              className={classNames(projectcss.all, sty.image40)}
            />

            <div
              data-plasmic-name={"image41"}
              data-plasmic-override={overrides.image41}
              className={classNames(projectcss.all, sty.image41)}
            />

            <div
              data-plasmic-name={"image42"}
              data-plasmic-override={overrides.image42}
              className={classNames(projectcss.all, sty.image42)}
            />

            <div
              data-plasmic-name={"image43"}
              data-plasmic-override={overrides.image43}
              className={classNames(projectcss.all, sty.image43)}
            />

            <div
              data-plasmic-name={"image44"}
              data-plasmic-override={overrides.image44}
              className={classNames(projectcss.all, sty.image44)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ljdlF
              )}
            >
              {"首页"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___7OrWe
              )}
            >
              {"关于沐融"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__l6T1
              )}
            >
              {"产品&解决方案"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jK6So
              )}
            >
              {"IT服务"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__n9Yu
              )}
            >
              {"成功案例"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___4DfB9
              )}
            >
              {"新闻中心"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___9H7L2
              )}
            >
              {"加入沐融"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__fOqZ
              )}
            >
              {"合作伙伴"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__w63NF
              )}
            >
              {"联系我们"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__maCl5
              )}
            >
              {"中文"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__rERb
              )}
            >
              {"|"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ic1Nu
              )}
            >
              {"EN"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___8AtK4
              )}
            >
              {"主营业务"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__heh1N
              )}
            >
              {"Main business"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__h1L9P
              )}
            >
              {"银行"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___4XuFz
              )}
            >
              {"支付机构"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___4W2I2
              )}
            >
              {"保险"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__wbls4
              )}
            >
              {"基金"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__vOlqn
              )}
            >
              {"消费金融"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__f4Fxo
              )}
            >
              {"企业金融"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__uNaM6
              )}
            >
              {"智慧城市"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__vXymR
              )}
            >
              {"技术平台"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__b5Rsq
              )}
            >
              {"关于我们"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__xqeWi
              )}
            >
              {"About us"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__bgrM
              )}
            >
              {"关于我们"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ylxHw
              )}
            >
              {"管理团队"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___2Kz4
              )}
            >
              {"企业文化"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___4Wntw
              )}
            >
              {"发展历程"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__l13MH
              )}
            >
              {"新闻中心"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__pfoRv
              )}
            >
              {"news center"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__msSo
              )}
            >
              {"公司动态"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___3WoVb
              )}
            >
              {"端午安康！"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mE7X
              )}
            >
              {"2022-06-01"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__wfMn
              )}
            >
              {"了解更多+"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__vjDkO
              )}
            >
              {"公司动态"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__rqE5Z
              )}
            >
              {"沐融科技中标渤海银行区块链供应链金融平台建设项目"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__rjMFj
              )}
            >
              {
                "近日，沐融科技再传捷报，中标渤海银行区块链供应链金融平台建设采购项目。"
              }
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___3Y0A
              )}
            >
              {"2022-06-01"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__qLwo8
              )}
            >
              {"了解更多+"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__bgYXw
              )}
            >
              {"公司动态"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mMgBg
              )}
            >
              {"沐融科技入围重庆农商行供应商"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__skBkX
              )}
            >
              {
                "近期，沐融科技凭借丰富的银行项目实施经验和优秀的软件开发服务能力，在众多公司中脱颖而出，成功入围重庆农商行软件开发外包服务供应商。"
              }
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___7Qox
              )}
            >
              {"2022-06-01"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___8YHZa
              )}
            >
              {"了解更多+"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___7JmoV
              )}
            >
              {"北京沐融信息科技股份有限公司"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__cnhE
              )}
            >
              {"全球领先的数字金融IT解决方案提供商"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__rF3J3
              )}
            >
              {"北京市海淀区王庄路1号清华同方科技广场B座10层"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__psaLq
              )}
            >
              {"京ICP备15000632号-1"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__xMkW5
              )}
            >
              {"Copyright @ 北京沐融信息科技股份有限公司"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__cii08
              )}
            >
              {"联系我们"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__xLjOr
              )}
            >
              {"电话"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__u8AoK
              )}
            >
              {"010-82415248"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__u3Rcf
              )}
            >
              {"地址"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__rjzwt
              )}
            >
              {"北京市海淀区王庄路1号清华同方科技广场B座10层"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__sag5E
              )}
            >
              {"手机号"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___1ZxgE
              )}
            >
              {"13701101545"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ar88C
              )}
            >
              {"邮箱"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ggLbc
              )}
            >
              {"market@murongtech.com"}
            </div>
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "frame",
    "rectangle",
    "rectangle2",
    "image",
    "rectangle3",
    "image2",
    "rectangle4",
    "rectangle5",
    "rectangle6",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "image3",
    "rectangle11",
    "image4",
    "rectangle12",
    "image5",
    "rectangle13",
    "image6",
    "rectangle14",
    "image7",
    "rectangle15",
    "image8",
    "rectangle16",
    "image9",
    "rectangle17",
    "rectangle18",
    "rectangle19",
    "rectangle20",
    "rectangle21",
    "rectangle22",
    "rectangle23",
    "rectangle24",
    "rectangle25",
    "rectangle26",
    "rectangle27",
    "rectangle28",
    "rectangle29",
    "image10",
    "image11",
    "rectangle30",
    "image12",
    "image13",
    "rectangle31",
    "image14",
    "image15",
    "rectangle32",
    "image16",
    "image17",
    "rectangle33",
    "image18",
    "image19",
    "rectangle34",
    "image20",
    "image21",
    "rectangle35",
    "image22",
    "image23",
    "rectangle36",
    "image24",
    "image25",
    "image26",
    "rectangle37",
    "rectangle38",
    "rectangle39",
    "rectangle40",
    "rectangle41",
    "rectangle42",
    "rectangle43",
    "rectangle44",
    "image27",
    "rectangle45",
    "image28",
    "rectangle46",
    "image29",
    "rectangle47",
    "image30",
    "rectangle48",
    "rectangle49",
    "rectangle50",
    "rectangle51",
    "rectangle52",
    "rectangle53",
    "rectangle54",
    "rectangle55",
    "image31",
    "image32",
    "rectangle56",
    "image33",
    "image34",
    "rectangle57",
    "image35",
    "image36",
    "rectangle58",
    "image37",
    "image38",
    "image39",
    "image40",
    "image41",
    "image42",
    "image43",
    "image44"
  ],

  frame: [
    "frame",
    "rectangle",
    "rectangle2",
    "image",
    "rectangle3",
    "image2",
    "rectangle4",
    "rectangle5",
    "rectangle6",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "image3",
    "rectangle11",
    "image4",
    "rectangle12",
    "image5",
    "rectangle13",
    "image6",
    "rectangle14",
    "image7",
    "rectangle15",
    "image8",
    "rectangle16",
    "image9",
    "rectangle17",
    "rectangle18",
    "rectangle19",
    "rectangle20",
    "rectangle21",
    "rectangle22",
    "rectangle23",
    "rectangle24",
    "rectangle25",
    "rectangle26",
    "rectangle27",
    "rectangle28",
    "rectangle29",
    "image10",
    "image11",
    "rectangle30",
    "image12",
    "image13",
    "rectangle31",
    "image14",
    "image15",
    "rectangle32",
    "image16",
    "image17",
    "rectangle33",
    "image18",
    "image19",
    "rectangle34",
    "image20",
    "image21",
    "rectangle35",
    "image22",
    "image23",
    "rectangle36",
    "image24",
    "image25",
    "image26",
    "rectangle37",
    "rectangle38",
    "rectangle39",
    "rectangle40",
    "rectangle41",
    "rectangle42",
    "rectangle43",
    "rectangle44",
    "image27",
    "rectangle45",
    "image28",
    "rectangle46",
    "image29",
    "rectangle47",
    "image30",
    "rectangle48",
    "rectangle49",
    "rectangle50",
    "rectangle51",
    "rectangle52",
    "rectangle53",
    "rectangle54",
    "rectangle55",
    "image31",
    "image32",
    "rectangle56",
    "image33",
    "image34",
    "rectangle57",
    "image35",
    "image36",
    "rectangle58",
    "image37",
    "image38",
    "image39",
    "image40",
    "image41",
    "image42",
    "image43",
    "image44"
  ],

  rectangle: ["rectangle"],
  rectangle2: ["rectangle2"],
  image: ["image"],
  rectangle3: ["rectangle3"],
  image2: ["image2"],
  rectangle4: ["rectangle4"],
  rectangle5: ["rectangle5"],
  rectangle6: ["rectangle6"],
  rectangle7: ["rectangle7"],
  rectangle8: ["rectangle8"],
  rectangle9: ["rectangle9"],
  rectangle10: ["rectangle10"],
  image3: ["image3"],
  rectangle11: ["rectangle11"],
  image4: ["image4"],
  rectangle12: ["rectangle12"],
  image5: ["image5"],
  rectangle13: ["rectangle13"],
  image6: ["image6"],
  rectangle14: ["rectangle14"],
  image7: ["image7"],
  rectangle15: ["rectangle15"],
  image8: ["image8"],
  rectangle16: ["rectangle16"],
  image9: ["image9"],
  rectangle17: ["rectangle17"],
  rectangle18: ["rectangle18"],
  rectangle19: ["rectangle19"],
  rectangle20: ["rectangle20"],
  rectangle21: ["rectangle21"],
  rectangle22: ["rectangle22"],
  rectangle23: ["rectangle23"],
  rectangle24: ["rectangle24"],
  rectangle25: ["rectangle25"],
  rectangle26: ["rectangle26"],
  rectangle27: ["rectangle27"],
  rectangle28: ["rectangle28"],
  rectangle29: ["rectangle29"],
  image10: ["image10"],
  image11: ["image11"],
  rectangle30: ["rectangle30"],
  image12: ["image12"],
  image13: ["image13"],
  rectangle31: ["rectangle31"],
  image14: ["image14"],
  image15: ["image15"],
  rectangle32: ["rectangle32"],
  image16: ["image16"],
  image17: ["image17"],
  rectangle33: ["rectangle33"],
  image18: ["image18"],
  image19: ["image19"],
  rectangle34: ["rectangle34"],
  image20: ["image20"],
  image21: ["image21"],
  rectangle35: ["rectangle35"],
  image22: ["image22"],
  image23: ["image23"],
  rectangle36: ["rectangle36"],
  image24: ["image24"],
  image25: ["image25"],
  image26: ["image26"],
  rectangle37: ["rectangle37"],
  rectangle38: ["rectangle38"],
  rectangle39: ["rectangle39"],
  rectangle40: ["rectangle40"],
  rectangle41: ["rectangle41"],
  rectangle42: ["rectangle42"],
  rectangle43: ["rectangle43"],
  rectangle44: ["rectangle44"],
  image27: ["image27"],
  rectangle45: ["rectangle45"],
  image28: ["image28"],
  rectangle46: ["rectangle46"],
  image29: ["image29"],
  rectangle47: ["rectangle47"],
  image30: ["image30"],
  rectangle48: ["rectangle48"],
  rectangle49: ["rectangle49"],
  rectangle50: ["rectangle50"],
  rectangle51: ["rectangle51"],
  rectangle52: ["rectangle52"],
  rectangle53: ["rectangle53"],
  rectangle54: ["rectangle54"],
  rectangle55: ["rectangle55"],
  image31: ["image31"],
  image32: ["image32"],
  rectangle56: ["rectangle56"],
  image33: ["image33"],
  image34: ["image34"],
  rectangle57: ["rectangle57"],
  image35: ["image35"],
  image36: ["image36"],
  rectangle58: ["rectangle58"],
  image37: ["image37"],
  image38: ["image38"],
  image39: ["image39"],
  image40: ["image40"],
  image41: ["image41"],
  image42: ["image42"],
  image43: ["image43"],
  image44: ["image44"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    frame: makeNodeComponent("frame"),
    rectangle: makeNodeComponent("rectangle"),
    rectangle2: makeNodeComponent("rectangle2"),
    image: makeNodeComponent("image"),
    rectangle3: makeNodeComponent("rectangle3"),
    image2: makeNodeComponent("image2"),
    rectangle4: makeNodeComponent("rectangle4"),
    rectangle5: makeNodeComponent("rectangle5"),
    rectangle6: makeNodeComponent("rectangle6"),
    rectangle7: makeNodeComponent("rectangle7"),
    rectangle8: makeNodeComponent("rectangle8"),
    rectangle9: makeNodeComponent("rectangle9"),
    rectangle10: makeNodeComponent("rectangle10"),
    image3: makeNodeComponent("image3"),
    rectangle11: makeNodeComponent("rectangle11"),
    image4: makeNodeComponent("image4"),
    rectangle12: makeNodeComponent("rectangle12"),
    image5: makeNodeComponent("image5"),
    rectangle13: makeNodeComponent("rectangle13"),
    image6: makeNodeComponent("image6"),
    rectangle14: makeNodeComponent("rectangle14"),
    image7: makeNodeComponent("image7"),
    rectangle15: makeNodeComponent("rectangle15"),
    image8: makeNodeComponent("image8"),
    rectangle16: makeNodeComponent("rectangle16"),
    image9: makeNodeComponent("image9"),
    rectangle17: makeNodeComponent("rectangle17"),
    rectangle18: makeNodeComponent("rectangle18"),
    rectangle19: makeNodeComponent("rectangle19"),
    rectangle20: makeNodeComponent("rectangle20"),
    rectangle21: makeNodeComponent("rectangle21"),
    rectangle22: makeNodeComponent("rectangle22"),
    rectangle23: makeNodeComponent("rectangle23"),
    rectangle24: makeNodeComponent("rectangle24"),
    rectangle25: makeNodeComponent("rectangle25"),
    rectangle26: makeNodeComponent("rectangle26"),
    rectangle27: makeNodeComponent("rectangle27"),
    rectangle28: makeNodeComponent("rectangle28"),
    rectangle29: makeNodeComponent("rectangle29"),
    image10: makeNodeComponent("image10"),
    image11: makeNodeComponent("image11"),
    rectangle30: makeNodeComponent("rectangle30"),
    image12: makeNodeComponent("image12"),
    image13: makeNodeComponent("image13"),
    rectangle31: makeNodeComponent("rectangle31"),
    image14: makeNodeComponent("image14"),
    image15: makeNodeComponent("image15"),
    rectangle32: makeNodeComponent("rectangle32"),
    image16: makeNodeComponent("image16"),
    image17: makeNodeComponent("image17"),
    rectangle33: makeNodeComponent("rectangle33"),
    image18: makeNodeComponent("image18"),
    image19: makeNodeComponent("image19"),
    rectangle34: makeNodeComponent("rectangle34"),
    image20: makeNodeComponent("image20"),
    image21: makeNodeComponent("image21"),
    rectangle35: makeNodeComponent("rectangle35"),
    image22: makeNodeComponent("image22"),
    image23: makeNodeComponent("image23"),
    rectangle36: makeNodeComponent("rectangle36"),
    image24: makeNodeComponent("image24"),
    image25: makeNodeComponent("image25"),
    image26: makeNodeComponent("image26"),
    rectangle37: makeNodeComponent("rectangle37"),
    rectangle38: makeNodeComponent("rectangle38"),
    rectangle39: makeNodeComponent("rectangle39"),
    rectangle40: makeNodeComponent("rectangle40"),
    rectangle41: makeNodeComponent("rectangle41"),
    rectangle42: makeNodeComponent("rectangle42"),
    rectangle43: makeNodeComponent("rectangle43"),
    rectangle44: makeNodeComponent("rectangle44"),
    image27: makeNodeComponent("image27"),
    rectangle45: makeNodeComponent("rectangle45"),
    image28: makeNodeComponent("image28"),
    rectangle46: makeNodeComponent("rectangle46"),
    image29: makeNodeComponent("image29"),
    rectangle47: makeNodeComponent("rectangle47"),
    image30: makeNodeComponent("image30"),
    rectangle48: makeNodeComponent("rectangle48"),
    rectangle49: makeNodeComponent("rectangle49"),
    rectangle50: makeNodeComponent("rectangle50"),
    rectangle51: makeNodeComponent("rectangle51"),
    rectangle52: makeNodeComponent("rectangle52"),
    rectangle53: makeNodeComponent("rectangle53"),
    rectangle54: makeNodeComponent("rectangle54"),
    rectangle55: makeNodeComponent("rectangle55"),
    image31: makeNodeComponent("image31"),
    image32: makeNodeComponent("image32"),
    rectangle56: makeNodeComponent("rectangle56"),
    image33: makeNodeComponent("image33"),
    image34: makeNodeComponent("image34"),
    rectangle57: makeNodeComponent("rectangle57"),
    image35: makeNodeComponent("image35"),
    image36: makeNodeComponent("image36"),
    rectangle58: makeNodeComponent("rectangle58"),
    image37: makeNodeComponent("image37"),
    image38: makeNodeComponent("image38"),
    image39: makeNodeComponent("image39"),
    image40: makeNodeComponent("image40"),
    image41: makeNodeComponent("image41"),
    image42: makeNodeComponent("image42"),
    image43: makeNodeComponent("image43"),
    image44: makeNodeComponent("image44"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
